history.scrollRestoration='manual';
const app=document.querySelector('#app'), controls=document.querySelector('#controls');
const TOTAL_PAGES=10,CHAPTER_PAGES=[2,4,8],CHAPTER_NAMES=['Work in progress','Learning & exploration','Reading & reflection'];
let page=Math.min(TOTAL_PAGES,Math.max(1,Number(location.hash.slice(1))||1)),busy=false,promptRound=0;
const garden='https://xuxinsienna.github.io/four-seasons-garden-260919/';
const steps='https://my.feishu.cn/wiki/AGvTwriR6iQqAmk8l2KcF8Zgnhh?from=from_copylink';
const record='https://www.doubao.com/thread/xQzRVdCYJxMcGjDYc';
const arrow=(next,label='Next page')=>`<button class="arrow" data-go="${next}" aria-label="${next===TOTAL_PAGES?'查看致谢页':'下一页'}"><span>${label}</span><svg viewBox="0 0 85 43" aria-hidden="true"><path d="M5 30 Q30 10 65 19 M51 5 L76 19 55 36 M7 34 Q30 17 65 21"/></svg></button>`;
const meta=chapter=>`<div class="page-meta"><span class="eyebrow">${CHAPTER_NAMES[chapter]}</span></div>`;
const projectHeading=(number,category,title)=>`<p class="eyebrow red project-kicker"><span class="project-index">${number}</span> · ${category}</p><h2 class="project-title">${title}</h2>`;
const rings='<div class="rings" aria-hidden="true"><img src="assets/rings.png" alt=""></div>';
const tabs=(active)=>`<nav class="tabs" aria-label="章节切换">${['工作汇报','学习提升','反思感悟'].map((s,i)=>`<button class="${i===active?'active':''}" aria-current="${i===active?'page':'false'}" data-chapter="${i}" data-go="${CHAPTER_PAGES[i]}">${s}</button>`).join('')}</nav>`;
const holes=(side)=>`<div class="punches ${side}" aria-hidden="true">${[16.6,27.2,37.2,64.1,74,84.4].map(x=>`<i style="left:${x}%"></i>`).join('')}</div>`;
const binder=(a,b,active,extra='')=>`<article class="binder chapter-${active} ${extra}">${tabs(active)}<section class="sheet sheet-upper">${a}${holes('bottom')}</section>${rings}<section class="sheet sheet-lower">${holes('top')}${b}</section></article>`;
const divider=(n,zh,en,desc,next,cls='')=>`<article class="binder chapter-divider chapter-${n-1}">${tabs(n-1)}<section class="sheet sheet-upper divider-sheet ${cls}"><p class="eyebrow red">September notebook / chapter 0${n}</p><div class="divider-layout"><span class="chapter-number">0${n}</span><div><h2>${zh}</h2><h3 class="divider-en">${en}</h3><p class="divider-description">${desc}</p></div></div>${arrow(next,'Open chapter')}${holes('bottom')}</section>${rings}</article>`;
function screenMarkup(n){
 const screens=[
 ()=>``,
 ()=>`<article class="spread"><section class="title-leaf"><span class="eyebrow">September · 2026</span><h1>Monthly<br><i>Learning</i><br>& <i>Sharing</i><br>Session</h1><span class="signature">Xin</span><span class="date">2026 / 09 / 28</span></section><img class="toc-hardware" src="assets/rings.png" alt=""><section class="toc"><p class="eyebrow red">In this notebook</p><h2>Contents</h2><p class="small muted">目录</p>${['工作汇报','学习提升','反思感悟'].map((s,i)=>`<button class="toc-item" data-go="${CHAPTER_PAGES[i]}"><span>0${i+1}</span><span><strong>${s}</strong><small>${CHAPTER_NAMES[i]}</small></span></button>`).join('')}${arrow(2,'Let’s begin')}</section></article>`,
 ()=>divider(1,'工作汇报','Work in progress','Content Reuse / Product Manual',3),
 ()=>binder(`${meta(0)}<div class="work-section"><h2 class="lead">Content Reuse</h2><p>协助完成 Maintenance Manual 收尾</p></div><div class="work-section"><h2 class="lead">Product Manual</h2><h3 class="status-title">Completed</h3><ul class="work-items"><li><span>Cu-S Installation Manual 和 SPM</span><span class="stamp">APPROVED</span></li><li><span>Sirius Maintenance Manual</span><span class="stamp">APPROVED</span></li></ul></div>${arrow(3,'Scroll down ↓')}`,
 `${meta(0)}<div class="work-section work-continuation"><h2 class="lead">Product Manual</h2><h3 class="status-title">In progress</h3><ul class="work-items"><li>Fortano HT14 DHD SPM 已收到 input 并开始更新</li><li>Cu-S safety manual 预计 9/30 前收到 input</li></ul><h3 class="status-title coming-up">Coming up</h3><ul class="work-items"><li>超微 CD-SEM 项目预计 11 月初开始陆续拿到 input</li></ul></div>${arrow(4,'Learning & exploration')}`,0),
 ()=>divider(2,'学习提升','Learning & exploration','从工作中的知识输入，到工作外的 AI 实践。',5,'stripe'),
 ()=>binder(`${meta(1)}<p class="eyebrow red">Part one · 工作中的学习</p><div class="row wide-left learning-grid"><div><h3 class="section-title">AI-assisted Authoring<br>Workgroup</h3><ul class="item-list"><li><strong>把想法变成作品——</strong><br><span class="small">我的 Vibe Coding 实践与思考</span></li><li>DTD、XSD、Schematron、XSLT 和 JSON Schema <span class="person">Tiffany</span></li><li>Convert Formula Image to MathML <span class="person">Rey</span></li><li>Translation skill <span class="person">Flora</span></li><li>Create Troubleshooting & BKM <span class="person">Erin</span></li></ul></div><div><h3 class="section-title">Knowledge Sharing</h3><ul class="item-list"><li>UI 国际化设计和 AI 应用 <span class="person">Erin</span></li><li>为复杂概念而设计：构建科普视频的结构化叙事与多模态表达 <span class="person">Lynn</span></li><li>让技术信息更友好：错误码内容管理的智能化实践 <span class="person">Tiffany</span></li></ul><div class="work-note"><h3 class="section-title">New Hire Training</h3><p class="small">Department role and organization structure</p><p class="small">Overview of workflow and process</p></div></div></div>${arrow(5,'Scroll down ↓')}`,
 `${meta(1)}<p class="eyebrow red">中微大讲堂</p><h2>新型薄膜在<br>先进芯片制程中的应用</h2><div class="lecture-topics"><section><h3 class="topic-heading"><span>01</span>Mo 和 Ru 的特性和应用</h3></section><section><h3 class="topic-heading"><span>02</span>前驱体的发展方向</h3><table class="lecture-table"><tbody>${[['01','形态','液体主导 → 固液并重','先进制程催生固体化'],['02','纯度逻辑','越纯越好 → 配方制胜','配方与杂质谱控制成核心'],['03','适配逻辑','通用标准品 → 机台定制','配方与机台 / 设备 / 容器深度绑定'],['04','材料维度','三维薄膜 → 低维材料','二维 / 一维薄膜成为前沿方向'],['05','研发范式','经验试错 → 计算 + 机理','分子设计前移、开发提速']].map(r=>`<tr><td>${r[1]}</td><td>${r[2]}<small>${r[3]}</small></td></tr>`).join('')}</tbody></table></section></div>${arrow(6,'Beyond the workday')}`,1),
 ()=>binder(`${meta(1)}<p class="eyebrow red">Part two · 工作外的 AI 自学</p><div class="garden-intro"><div>${projectHeading('①','AI 3D creation','四季庭院')}<p class="lead">A garden for all seasons.</p></div><div><p>3D 庭院场景，展现四季更迭与昼夜更替。<br>适合挂机使用。</p><p class="small">门、灯、猫、树冠和溪流支持点击交互。</p><div style="margin-top:18px"><span class="pill">Three.js</span><span class="pill">React</span><span class="pill">TypeScript</span></div></div></div><div class="screen-wide"><iframe title="四季庭院交互演示" src="${garden}" loading="lazy" allow="fullscreen" allowfullscreen></iframe></div><div class="media-links"><a href="${garden}" target="_blank" rel="noopener">独立窗口打开庭院 ↗</a><button id="garden-full">放大庭院 ↗</button></div>${arrow(6,'Scroll down ↓')}`,
 `${meta(1)}<div class="media-layout"><div>${projectHeading('②','AI film','猫咪<br>新品发布会')}<p class="lead">Meet Mi Duo.</p><p class="project-caption">仿手机发布会风格，让「咪咪」成为这次发布会的主角。</p><div class="media-links"><a href="${steps}" target="_blank" rel="noopener">制作步骤 ↗</a><a href="${record}" target="_blank" rel="noopener">AI 使用记录 ↗</a></div></div><div class="tv"><div class="tv-screen"><video id="cat-video" controls preload="metadata" playsinline src="assets/cat-launch.mp4" aria-label="猫咪新品发布会视频"></video></div><img src="assets/tv.png" alt="复古红色电视机"></div></div><div class="media-links" style="justify-content:flex-end"><button id="video-full">放大播放 ↗</button></div><div class="prompt-panel"><div class="prompt-tabs" role="tablist" aria-label="提示词轮次"><button role="tab" id="round-0" aria-controls="prompt-code" aria-selected="true" data-prompt="0">第一轮 · 完整脚本</button><button role="tab" id="round-1" aria-controls="prompt-code" aria-selected="false" data-prompt="1">第二轮 · 局部调整</button><button class="copy" id="copy-prompt">复制全文</button></div><pre id="prompt-code" role="tabpanel" aria-labelledby="round-0" tabindex="0"></pre></div>${arrow(7,'ID 删除工具')}`,1),
 ()=>binder(`${meta(1)}${projectHeading('③','AI tool','ID 删除工具')}<p class="project-caption tool-description">扫描 DITA 文件（<code>.dita</code> / <code>.ditamap</code> / <code>.xml</code>），找出<strong>没有任何引用机制使用</strong>的元素 <code>id</code> 属性，生成报告，待人工确认后删除。</p><div class="prompt-panel tool-guide-panel"><div class="prompt-tabs"><span id="tool-guide-label">工具说明</span><button class="copy" id="copy-tool-guide">复制全文</button></div><pre id="tool-guide" aria-labelledby="tool-guide-label" tabindex="0"></pre></div>${arrow(7,'Scroll down ↓')}`,`${meta(1)}<div class="demo-page"><h2 class="demo-title">Demo</h2></div>${arrow(8,'Reading & reflection')}`,1,'tool-binder'),
 ()=>divider(3,'反思感悟','Reading & reflection','Lean In · Women, Work, and the Will to Lead',9),
 ()=>binder(`${meta(2)}<div class="row"><div><p class="eyebrow red">Reading notes</p><div class="book-title">Lean In</div><p class="book-subtitle">Women, Work,<br>and the Will to Lead</p><div class="work-note"><h3 class="en">Sheryl Sandberg</h3><p class="author-role en">Chief operating officer of Meta Platforms (2008–2022)</p></div></div><div><img class="book-cover" src="assets/lean-in.png" alt="Lean In: Women, Work, and the Will to Lead，Sheryl Sandberg 著，书籍封面"></div></div>${arrow(9,'Scroll down ↓')}`,
 `${meta(2)}<h2>向前一步</h2><p class="quote">What would you do<br>if you weren’t afraid?</p><div class="reading-columns"><ol class="reading-list">${["The Leadership Ambition Gap:<br>What Would You Do if You Weren't Afraid?","Sit at the Table","Success and Likability","It's a Jungle Gym, Not a Ladder","Are You My Mentor?","Seek and Speak Your Truth","Don't Leave Before You Leave","Make Your Partner a Real Partner","The Myth of Doing It All","Let's Start Talking About It","Working Together Toward Equality"].map((s,i)=>`${i===6?'</ol><ol class="reading-list" start="7">':''}<li class="${i<2?'emphasis':''}">${s}</li>`).join('')}</ol></div>${arrow(10,'')}`,2),
 ()=>`<article class="binder chapter-divider thanks-binder">${tabs(-1)}<section class="sheet sheet-upper divider-sheet thanks-sheet"><p class="eyebrow red">September notebook / Xin</p><h2 class="thanks-title">Thank you<br>for listening.</h2>${holes('bottom')}</section>${rings}</article>`
 ];
 return screens[n]();
}
function addBacking(book){
 const backing=document.createElement('div');backing.className='notebook-backing';backing.setAttribute('aria-hidden','true');
 backing.append(document.createElement('div'));book.prepend(backing);return backing;
}
function render(){
 controls.hidden=false; document.querySelector('#position').textContent=`${String(page).padStart(2,'0')} / ${String(TOTAL_PAGES).padStart(2,'0')}`;
 app.replaceChildren(buildNotebook(page,screenMarkup(page)));sizeNotebook(page===1);window.scrollTo({top:0,behavior:'instant'});
 if(page===6)updatePrompt(0);
 if(page===7)document.querySelector('#tool-guide').textContent=TOOL_GUIDE;
}
function updatePrompt(n){promptRound=n;document.querySelectorAll('[data-prompt]').forEach(b=>b.setAttribute('aria-selected',String(+b.dataset.prompt===n)));let p=document.querySelector('#prompt-code');p.textContent=PROMPTS[n];p.scrollTop=0;p.setAttribute('aria-labelledby',`round-${n}`)}
async function go(n){n=Math.max(1,Math.min(TOTAL_PAGES,n));if(busy)return;if(n===page){document.querySelectorAll('.sheet')[1]?.scrollIntoView({behavior:'smooth',block:'start'});return}busy=true;document.querySelectorAll('video').forEach(v=>v.pause());const rotate=page===1&&CHAPTER_PAGES.includes(n);const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;try{if(rotate&&!reduce){await rotateNotebookTo(n);}else{page=n;history.replaceState(null,'','#'+n);render();}}finally{busy=false;}}
document.addEventListener('click',async e=>{let b=e.target.closest('[data-go]');if(b){if(b.hasAttribute('data-chapter')&&b.getAttribute('aria-current')==='page')return;go(+b.dataset.go);return}b=e.target.closest('[data-prompt]');if(b){updatePrompt(+b.dataset.prompt);return}if(e.target.id==='copy-tool-guide'){const button=e.target;try{await navigator.clipboard.writeText(TOOL_GUIDE);button.textContent='已复制'}catch{button.textContent='请选中正文复制'}setTimeout(()=>{if(button.isConnected)button.textContent='复制全文'},1800);return}if(e.target.id==='copy-prompt'){try{await navigator.clipboard.writeText(PROMPTS[promptRound]);e.target.textContent='已复制'}catch{e.target.textContent='请选中正文复制'}setTimeout(()=>{if(document.querySelector('#copy-prompt'))document.querySelector('#copy-prompt').textContent='复制全文'},1800)}if(e.target.id==='video-full'){let v=document.querySelector('#cat-video');if(v.requestFullscreen)await v.requestFullscreen().catch(()=>{});else if(v.webkitEnterFullscreen)v.webkitEnterFullscreen()}if(e.target.id==='garden-full')document.querySelector('.screen-wide iframe')?.requestFullscreen?.().catch(()=>{});});
document.querySelector('#back').onclick=()=>go(Math.max(1,page-1));document.querySelector('#home').onclick=()=>go(1);document.querySelector('#fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>{})};
document.addEventListener('keydown',e=>{if(e.target.closest('video,iframe,pre,button,a,input,textarea'))return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();go(Math.min(TOTAL_PAGES,page+1))}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(Math.max(1,page-1))}if(e.key==='Escape'&&!document.fullscreenElement)go(1)});render();




